- name: Dnf install bind and bind-utils
  ansible.builtin.dnf:
    name: [ 'bind', 'bind-utils' ]
    state: latest

- name: Add DNS service
  ansible.posix.firewalld:
    service: dns
    permanent: yes
    state: enabled

- name: Open port 53/TCP for DNS
  ansible.posix.firewalld:
    port: 53/tcp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Open port 53/UDP for DNS
  ansible.posix.firewalld:
    port: 53/udp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld service

- name: Open port 8301
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 8301/tcp
    - 8301/udp
  notify: Reload firewalld service

- name: Disable IPv6
  copy:
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present reload=yes sysctl_file=/etc/sysctl.d/70-ipv6.conf
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: Changing hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Insert template into hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Reboot vm
  reboot:
    reboot_timeout: 3600

- name: Create log directory
  file:
    path: /var/named/log
    state: directory
    mode: "0750"
    owner: named
    group: named

- name: Create file into /var/named/log
  file:
    path: /var/named/log/"{{ item }}"
    state: touch
    mode: "0640"
    owner: named
    group: named
  with_items:
    - default
    - auth_servers
    - zone_transfers
    - client_security
    - queries
    - query-errors

- name: Get cloud metadata
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    method: GET
    return_content: yes
    status_code: 200
  register: cloud_metadata

- name: Get reverse ip
  set_fact:
    reverse_ip: "{{ cloud_metadata.content.split('.')[0:3] | reverse | join('.') }}"
    last_octet: "{{ cloud_metadata.content.split('.')[-1] }}"

- name: Add zone file
  template:
    src: zonefile.j2
    dest: /etc/named/{{ hostname }}.{{ domain_name }}
    owner: root
    group: named
    mode: '0644'
  notify: Restart named

- name: Copy named to /etc/named.conf
  template:
    src: named.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'
  notify: Restart named

- name: Copy resolv.conf
  template:
    src: resolv.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart named

- name: Copy reverse zone file
  template:
    src: reverse.j2
    dest: /etc/named/reverse.{{ hostname }}.{{ domain_name }}
    owner: root
    group: named
    mode: '0644'
  notify: Restart named

#  Fix permissions
- name: Change ownership of /etc/named.conf
  file:
    path: /etc/named.conf
    owner: named
    group: named
    mode: '0640'

- name: Change ownership of /var/named/
  file:
    path: /var/named/
    owner: named
    group: named
    recurse: yes

- name: Change ownership of /var/log/named/
  file:
    path: /var/log/named/
    owner: named
    group: named
    recurse: yes

- name: Change permissions of /var/named/
  file:
    path: /var/named/
    mode: '0750'
    recurse: yes

- name: Change permissions of /var/log/named/
  file:
    path: /var/log/named/
    mode: '0750'
    recurse: yes

- name: Flush handlers
  meta: flush_handlers
