apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
  - name: http-metrics
    protocol: TCP
    port: 3100
    targetPort: 3100
    nodePort: 30310
  type: NodePort
