apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: prometheus
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 30910
  type: NodePort
