apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30909
  type: NodePort
